import type { DependencyPath } from "@/lib/types";
type Manifest={name?:string;dependencies?:Record<string,string>};type LockPackage={version?:string;license?:string;dependencies?:Record<string,string>};type Legacy={version?:string;dependencies?:Record<string,Legacy>};type PackageLock={lockfileVersion?:number;packages?:Record<string,LockPackage>;dependencies?:Record<string,Legacy>};
export type InstalledDependency={key:string;name:string;version:string;direct:boolean;license:string;paths:DependencyPath[]};
export class ManifestError extends Error{constructor(message:string,public readonly code:"INVALID_MANIFEST"|"NO_LOCKFILE"){super(message);this.name="ManifestError"}}
export function parseManifest(text:string):Manifest{try{const value=JSON.parse(text) as Manifest;if(!value||typeof value!=="object")throw new Error();return value}catch{throw new ManifestError("package.json is not valid JSON.","INVALID_MANIFEST")}}
export function parseLockfile(text?:string):PackageLock{if(!text?.trim())throw new ManifestError("package-lock.json is required for a reproducible dependency scan.","NO_LOCKFILE");try{const value=JSON.parse(text) as PackageLock;if(!value||typeof value!=="object")throw new Error();return value}catch{throw new ManifestError("package-lock.json is not valid JSON.","INVALID_MANIFEST")}}
export function extractDependencyGraph(manifest:Manifest,lock:PackageLock){return lock.packages&&Object.keys(lock.packages).length?modern(manifest,lock.packages):legacy(manifest,lock.dependencies??{})}
function modern(manifest:Manifest,packages:Record<string,LockPackage>):InstalledDependency[]{const project=manifest.name??"Application",directNames=new Set(Object.keys(manifest.dependencies??{})),paths=new Map<string,string[][]>(),queue:Array<{key:string;chain:string[]}>=[];for(const name of directNames){const key=resolve("",name,packages);if(key)queue.push({key,chain:[project,`${name}@${packages[key]?.version??"unknown"}`]})}const edges=new Set<string>();while(queue.length){const current=queue.shift()!,known=paths.get(current.key)??[];if(!known.some(p=>p.join("\0")===current.chain.join("\0"))){known.push(current.chain);paths.set(current.key,known.slice(0,20))}for(const child of Object.keys(packages[current.key]?.dependencies??{})){const key=resolve(current.key,child,packages),edge=`${current.key}>${key}>${current.chain.join("\0")}`;if(!key||edges.has(edge)||current.chain.length>64)continue;edges.add(edge);queue.push({key,chain:[...current.chain,`${child}@${packages[key]?.version??"unknown"}`]})}}return Object.entries(packages).filter(([key,v])=>paths.has(key)&&key.includes("node_modules/")&&Boolean(v.version)).map(([key,v])=>{const name=nameFromKey(key),dependencyPaths=(paths.get(key)??[]).map(toPath);return{key,name,version:v.version!,direct:directNames.has(name)&&dependencyPaths.some(p=>p.nodes.length===2),license:v.license??"Unknown",paths:dependencyPaths}})}
function legacy(manifest:Manifest,deps:Record<string,Legacy>){const project=manifest.name??"Application",direct=new Set(Object.keys(manifest.dependencies??{})),result:InstalledDependency[]=[];const walk=(values:Record<string,Legacy>,chain:string[],parent:string)=>{for(const[name,v]of Object.entries(values)){const key=parent?`${parent}/node_modules/${name}`:`node_modules/${name}`,node=`${name}@${v.version??"unknown"}`;result.push({key,name,version:v.version??"unknown",direct:chain.length===1&&direct.has(name),license:"Unknown",paths:[toPath([...chain,node])]});walk(v.dependencies??{},[...chain,node],key)}};walk(deps,[project],"");return result}
function resolve(parent:string,child:string,packages:Record<string,LockPackage>){let cursor=parent;while(true){const candidate=cursor?`${cursor}/node_modules/${child}`:`node_modules/${child}`;if(packages[candidate])return candidate;const index=cursor.lastIndexOf("/node_modules/");if(index<0)break;cursor=cursor.slice(0,index)}return packages[`node_modules/${child}`]?`node_modules/${child}`:undefined}
function nameFromKey(key:string){const marker="node_modules/";return key.slice(key.lastIndexOf(marker)+marker.length)}function toPath(nodes:string[]):DependencyPath{return{nodes,display:nodes.join(" → ")}}
