"use client";
import{useMemo,useState}from"react";
import{Background,Controls,MarkerType,ReactFlow,type Node}from"@xyflow/react";
import"@xyflow/react/dist/style.css";
import{CheckCircle2,LoaderCircle,Play,RotateCcw,TerminalSquare,TriangleAlert}from"lucide-react";
import type{Dependency}from"@/lib/types";
import{remediationLabel}from"@/lib/remediation";
import{Button}from"./ui/button";
import{Badge}from"./ui/badge";

type Replay={demo:string;dependency:string;before:string|null;observed:string|null;vulnerable:boolean;cleanupVerified:boolean;safety:string};
type State={kind:"idle"}|{kind:"loading"}|{kind:"success";result:Replay}|{kind:"error";message:string};
const nodeStyle={background:"#11151c",border:"1px solid #272d37",borderRadius:10,color:"#f3f0e8",padding:14,width:190,fontSize:12};

export function AttackReplayPanel({dependency}:{dependency:Dependency}){
  const[state,setState]=useState<State>({kind:"idle"}),vulnerability=dependency.vulnerabilities[0],supported=dependency.name==="lodash"&&dependency.version==="4.17.11",ran=state.kind==="success",label=remediationLabel(dependency);
  const nodes=useMemo<Node[]>(()=>[{id:"input",position:{x:0,y:100},data:{label:"Fixed in-memory fixture"},style:nodeStyle},{id:"route",position:{x:250,y:100},data:{label:"Local proof route"},style:nodeStyle},{id:"dependency",position:{x:500,y:100},data:{label:`${dependency.name}@${dependency.version}`},style:{...nodeStyle,border:"1px solid #f05252"}},{id:"impact",position:{x:750,y:100},data:{label:ran?"Marker observable":"Application object boundary"},style:{...nodeStyle,border:`1px solid ${ran?"#f05252":"#e5a93d"}`}}],[dependency.name,dependency.version,ran]);
  const edges=[["input","route"],["route","dependency"],["dependency","impact"]].map(([source,target],index)=>({id:String(index),source,target,animated:ran,markerEnd:{type:MarkerType.ArrowClosed,color:"#e87b3e"},style:{stroke:"#e87b3e",strokeWidth:2}}));
  async function run(){setState({kind:"loading"});try{const response=await fetch("/api/attack-replay",{method:"POST"}),body=await response.json() as{data?:Replay;error?:{message?:string}};if(!response.ok||!body.data)throw new Error(body.error?.message??"The replay did not complete.");setState({kind:"success",result:body.data})}catch(error){setState({kind:"error",message:error instanceof Error?error.message:"The replay did not complete."})}}
  const output=state.kind==="success"?`[safe-demo] Fixed fixture created in memory\n[trace] POST /demo/prototype-pollution\n[trace] Dependency: ${state.result.dependency}\n[evidence] ${state.result.demo} · CVSS ${vulnerability?.cvss.toFixed(1)??"unavailable"}\n[result] Prototype marker observable: ${state.result.vulnerable?"YES":"NO"}\n[cleanup] Temporary marker removed: ${state.result.cleanupVerified?"YES":"NO"}\n[safety] ${state.result.safety}\n[remediation] Upgrade lodash to ${dependency.latest}, restart, and rescan.`:state.kind==="loading"?"[safe-demo] Contacting the fixed localhost fixture…":state.kind==="error"?`[error] ${state.message}\n[recovery] Run npm run demo:install, then npm run demo:start in another PowerShell window.`:"Ready. No request has been sent. The replay cannot accept a target, payload, or shell command.";
  return <section className="space-y-6" data-ui="attack-replay"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex flex-wrap items-center gap-2"><Badge tone="neutral">Isolated local demo</Badge><Badge tone={vulnerability?.severity==="unknown"?"neutral":vulnerability?.severity??"neutral"}>{vulnerability?.cveAlias??vulnerability?.id??"No CVE"}</Badge><span className="data text-xs text-muted-foreground">{dependency.name}@{dependency.version}</span></div><Button onClick={ran?()=>setState({kind:"idle"}):run} disabled={!supported||state.kind==="loading"}>{state.kind==="loading"?<LoaderCircle className="animate-spin" size={15}/>:ran?<RotateCcw size={15}/>:<Play size={15}/>} {state.kind==="loading"?"Running fixed proof…":ran?"Reset replay":"Run safe local replay"}</Button></div>{!supported?<div role="status" className="surface surface-outline flex gap-3 border-warning/35 p-4 text-sm"><TriangleAlert className="shrink-0 text-warning" size={18}/><p>This fixed replay supports only the teaching fixture <b>lodash@4.17.11</b>. Scan the <span className="data">vulnerable-demo</span> manifests and select that dependency.</p></div>:null}<div className="h-[320px] overflow-hidden rounded-md border bg-background sm:h-[390px]" data-ui="dependency-graph"><ReactFlow nodes={nodes} edges={edges} fitView minZoom={.4}><Background color="#272d37" gap={28} size={1}/><Controls showInteractive={false}/></ReactFlow></div><div className="surface surface-outline overflow-hidden"><div className="flex items-center gap-2 border-b px-4 py-3 text-xs text-muted-foreground"><TerminalSquare size={14}/>Local replay result</div><pre aria-live="polite" className={`scrollbar min-h-44 overflow-auto whitespace-pre-wrap p-5 font-mono text-xs leading-6 ${state.kind==="error"?"text-destructive":"text-muted-foreground"}`}>{output}</pre></div><div className="flex items-start gap-3 rounded-md border border-safe/20 bg-safe/5 p-4 text-sm"><CheckCircle2 className="mt-0.5 shrink-0 text-safe" size={18}/><div><b>{label??"Recommended remediation"}</b><p className="mt-1 text-muted-foreground">Run <span className="data">npm run demo:remediate</span>, restart the demo, upload its two manifests again, and compare the persisted scans. The fixed version no longer exhibits this behavior.</p></div></div></section>;
}
