import { ArrowDownRight, ArrowUpRight, GitCommitHorizontal } from "lucide-react";
import type { Scan } from "@/lib/types";
import { createSecurityDiff } from "@/lib/security-diff";

export function SecurityDiffLedger({ before, after }: { before: Scan; after: Scan }) {
  const diff = createSecurityDiff(before, after);
  return <section className="surface surface-outline" data-ui="security-diff"><div className="flex flex-col gap-4 border-b p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold">Structured security diff</h2><p className="mt-1 text-xs text-muted-foreground">Finding identity, dependency version, and attack-path evidence—not count changes alone.</p></div><span className="data text-xs text-muted-foreground">{diff.version}</span></div><div className="grid gap-px bg-border lg:grid-cols-3"><DiffColumn kind="removed" title="Removed risks" items={diff.findings.removed.map((item) => ({ id: item.cveAlias ?? item.vulnerabilityId, detail: `${item.dependencyName}@${item.dependencyVersion} · risk ${item.risk}` }))} /><DiffColumn kind="introduced" title="Added risks" items={diff.findings.introduced.map((item) => ({ id: item.cveAlias ?? item.vulnerabilityId, detail: `${item.dependencyName}@${item.dependencyVersion} · risk ${item.risk}` }))} /><DiffColumn kind="changed" title="Changed risks" items={diff.findings.changed.map((item) => ({ id: item.after.cveAlias ?? item.after.vulnerabilityId, detail: `${item.after.dependencyName} · ${item.changes.map((value) => value.field).join(", ")}` }))} /></div><div className="grid gap-px border-t bg-border sm:grid-cols-2 xl:grid-cols-4"><Metric label="Attack paths removed" value={diff.attackPaths.removed.length} good /><Metric label="New attack paths" value={diff.attackPaths.introduced.length} good={diff.attackPaths.introduced.length === 0} /><Metric label="Reachable critical" value={`${diff.metrics.reachableCriticalBefore} → ${diff.metrics.reachableCriticalAfter}`} good={diff.metrics.reachableCriticalChange <= 0} /><Metric label="Dependencies upgraded" value={diff.dependencies.upgraded.length} good /></div>{diff.dependencies.versionChanges.length ? <details className="border-t p-5"><summary className="cursor-pointer text-xs font-semibold text-primary">Dependency version changes ({diff.dependencies.versionChanges.length})</summary><ul className="data mt-4 grid gap-2 text-xs text-muted-foreground sm:grid-cols-2">{diff.dependencies.versionChanges.map((item) => <li key={item.dependencyKey} className="rounded-sm bg-background p-3 ring-1 ring-border">{item.name}: {item.beforeVersion} → {item.afterVersion} · {item.direction}</li>)}</ul></details> : null}</section>;
}

function DiffColumn({ title, kind, items }: { title: string; kind: "removed" | "introduced" | "changed"; items: Array<{ id: string; detail: string }> }) { const Icon = kind === "removed" ? ArrowDownRight : kind === "introduced" ? ArrowUpRight : GitCommitHorizontal; const tone = kind === "removed" ? "text-safe" : kind === "introduced" ? "text-destructive" : "text-warning"; return <div className="min-h-48 bg-card p-5"><div className={`flex items-center gap-2 ${tone}`}><Icon size={16} /><h3 className="text-sm font-semibold">{title}</h3><span className="data ml-auto text-xs">{items.length}</span></div>{items.length ? <ul className="mt-4 space-y-3">{items.slice(0, 8).map((item, index) => <li key={`${item.id}-${index}`}><b className={`data block text-xs ${tone}`}>{kind === "removed" ? "−" : kind === "introduced" ? "+" : "~"} {item.id}</b><span className="data mt-1 block break-words text-xs leading-5 text-muted-foreground">{item.detail}</span></li>)}</ul> : <p className="mt-5 text-xs text-muted-foreground">No {title.toLowerCase()}.</p>}</div>; }
function Metric({ label, value, good }: { label: string; value: string | number; good: boolean }) { return <div className="bg-card p-5"><span className="text-xs text-muted-foreground">{label}</span><b className={`data mt-1 block text-2xl ${good ? "text-safe" : "text-destructive"}`}>{value}</b></div>; }
