"use client";
import { ShieldCheck } from "lucide-react";
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from "recharts";
import type { Scan } from "@/lib/types";
import { severityCounts, severityOrder } from "@/lib/scan-selectors";
import { scanIsIncomplete } from "./source-coverage";

const colors={critical:"#f05252",high:"#ed783f",medium:"#e5a93d",low:"#35a58a",unknown:"#737b88"};
export function SeverityChart({scan}:{scan:Scan}){const counts=severityCounts(scan),data=severityOrder.map(name=>({name,value:counts[name],color:colors[name]})).filter(item=>item.value>0),total=data.reduce((sum,item)=>sum+item.value,0),incomplete=scanIsIncomplete(scan);if(total===0)return <div className="grid min-h-48 place-items-center text-center" data-ui="severity-chart"><div><span className={`mx-auto grid size-11 place-items-center rounded-full border ${incomplete?"border-warning/25 bg-warning/10 text-warning":"border-safe/25 bg-safe/10 text-safe"}`}><ShieldCheck size={20}/></span><b className="mt-3 block text-sm">{incomplete?"No findings from completed sources":"No known vulnerabilities"}</b><span className="mt-1 block text-xs text-muted-foreground">{incomplete?"Review scan coverage before accepting this result.":"The latest scan returned zero findings."}</span></div></div>;return <div className="grid items-center gap-2 sm:grid-cols-[1fr_150px]" data-ui="severity-chart"><div className="relative h-48"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={55} outerRadius={78} paddingAngle={2} stroke="none">{data.map(item=><Cell key={item.name} fill={item.color}/>)}</Pie><Tooltip contentStyle={{background:"#171c24",border:"1px solid #272d37",borderRadius:8,color:"#f3f0e8"}}/></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 grid place-items-center text-center"><span><b className="data block text-2xl">{total}</b><small className="text-muted-foreground">findings</small></span></div></div><div className="space-y-2">{data.map(item=><div key={item.name} className="flex items-center justify-between gap-4 text-xs"><span className="flex items-center gap-2 capitalize text-muted-foreground"><i className="size-2 rounded-full" style={{background:item.color}}/>{item.name}</span><b className="data">{item.value}</b></div>)}</div></div>}
